- hosts: web
  remote_user: root
  become: yes
  tasks:
    - name: "Updating and upgrading packages on the Server"
      shell:
        cmd: yum update -y && yum upgrade -y;

    - name: "Installing Terraform, output stored on terraform-version.txt"
      shell:
        cmd: |
          yum install -y yum-utils shadow-utils;
          yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo;
          yum install terraform -y;
          terraform --version > /home/ec2-user/terraform-version.txt;

    - name: "Install, start and enable Docker"
      shell:
        cmd: |
          yum install -y docker;
          gpasswd -a $USER docker;
          systemctl start docker;
          systemctl enable docker;

    - name: "Running hello-world image on docker, output stored on docker-out.txt"
      shell:
        cmd:
          docker run hello-world > /home/ec2-user/docker-out.txt;

    - name: "Install, start and enable Jenkins"
      shell:
        cmd: |
          yum update -y;
          wget -O /etc/yum.repos.d/jenkins.repo \
            https://pkg.jenkins.io/rpm-stable/jenkins.repo;
          rpm --import https://pkg.jenkins.io/rpm-stable/jenkins.io-2026.key;
          yum upgrade -y;
          yum install java-21-amazon-corretto -y;
          yum install jenkins -y;
          systemctl enable jenkins;
          systemctl start jenkins;
